
    public enum AgentFact
    {
        Fact_InvalidType = 0,
        InViewSight,
        PotentialEnemy,
        currentEnemy,
        PotentialPrey,
        MeleeWeapon,
        WeaponObject,
        InMeleeRange,
        InLungeRange,
        CanAttack,
        Blocking,
        StimuliInvestigated,
        DamageTaken,
        HasStamina,
        LowStamina,
        LowHealth,
        NeedMate,
        Hungry,
        Thirsty,
        HasNeed,
        PotentialMateInSight,
        Pregnant,
        Juvenile,
        RabbitBurrow,
        WolfDen,
        Tired,
        FoundMate,
        ForestBiome,
        InSpeciesBiome,
        CanEat,
        CanHeavyAttack,
        Attacking,
        Staggered,
        CanSpecialAttack,
        CanLungeAttack,
        EnemyAttacking,
        EnemyDefending,
        CanBreakBlock,
        CanDodge,
        RangeWeapon,
        MagicWeapon,
        InEnemyMeleeRange,
        AttackLanded,
        AuraCharged,
        CanChargeAura,
        CanUseUltimate,
        CanHearEnemy,
        HasMana,
        LowMana,
        EnemyAiming,
        EnemyChargingShot,
        EnemyExecutedShot,
        BlockedAttack,
        CounteredAttack,
        CanCounter,
        Repositioning,
        OpenDoor,
        NeedPath,
        Storage,
        AreaPlanted,
        AvailableSeat,
        HarvestablePlant,
        PlantedArea,
        AvailableWorkBench,
        NeedHealth,
        TargetFacingMe,
        LostTarget,
        TouchedStimulus,
        AtHome,
        HasFollowTarget
        
    }





